### ISSUE TITLE
Great experiment!

### ISSUE THREAD

**Issue by MaxGraey** [petersalomonsen/javascriptmusic#2]
Let me give some tips & tricks how you improve AS code more if you don't mind)

You don't need own `min/max/abs` for `f32` [here](https://github.com/petersalomonsen/javascriptmusic/blob/master/wasmaudioworklet/synth1/assembly/math/f32.ts#L2) because AS has builtin intrinsics for that which translates to single wasm opcodes like `f32.min/f32.max/f32.abs`. Just use `min<f32>(a, b)`, `max<f32>(a, b)` and `abs<f32>(x)`

**Comment by petersalomonsen** [comment]
Thank you very much! I appreciate a lot tips & tricks like that. The aim is to get small binaries and great performance so tips like these are really useful.

Also thanks for creating AssemblyScript. Been using WebAssembly / asm.js for a while now with different languages ( mostly c/c++ ), but found that AssemblyScript gives you most control of the generated webassembly.

**Comment by MaxGraey** [comment]
Thanks!
If you focus on small size. You shoud't use `@inline` decorator. Binaryen do this also well if necessary.
Also you could use additional tools like [`wasm-reduce`](https://github.com/WebAssembly/binaryen/blob/master/src/tools/wasm-reduce.cpp) which you got from original `binaryen` (you could install it via **brew** for example). Also wasm binaryen great compressable by **brotli**

**Comment by MaxGraey** [comment]
With `brotli -j -n -Z ./index.wasm` I got `2,673 bytes` instead `2,934 bytes` by gzip

**Comment by petersalomonsen** [comment]
Ohh that's great. I see most modern browsers support brotli. For my deployment of the synth at https://petersalomonsen.com/webassemblymusic/test1/ I used firebase hosting, which I think only does gzip - so would have to look at other hosting services maybe then?

**Comment by MaxGraey** [comment]
I recommend [now.sh](https://zeit.co/now). Docs: https://zeit.co/docs/v2/routing/compression

**Comment by petersalomonsen** [comment]
@MaxGraey Now got everything running in webassembly.studio. Check out the youtube video here: https://youtu.be/ThkIgYcvkMU ( link to webassembly.studio is in the video description ). Maybe you want to link this from your list of assemblyscript examples?

**Comment by MaxGraey** [comment]
@petersalomonsen really cool! You could open feature request issue in WebAssembly Studio repo about ability autorun script immediately after save. It will be great!

Also I saw you use custom **`sin`** function. Recently I invent very simple and small sin/cos with |sin x - s x| < 0.0007 which could be interested for your proposes. I know for most DSP algorithms 16-bit precision is quite enough. [See my twit](https://twitter.com/MaxGraey/status/1101621274588127232)

**Comment by petersalomonsen** [comment]
Great with minimalist sin function, don't need full precision for the audio stuff. I "stole" mine from a rust biquad filter, and I guess just a few more lines than yours: https://github.com/petersalomonsen/javascriptmusic/blob/master/wasmaudioworklet/synth1/assembly/math/sin.ts

How would you translate yours to assemblyscript? Need types, and what about the Math.floor and .PI constant? Are these built-ins? 

Autorun / build on save would be an improvement to the live-coding experience, so good tip!

**Comment by MaxGraey** [comment]
@petersalomonsen I create fiddle for you:
https://webassembly.studio/?f=3elqrnvbx2v

**Comment by MaxGraey** [comment]
If you don't use stdlib from AS und specify `--noLib` you could rewrite this code to:
```ts
const PI: f32 = 3.141592653589793;
export function sin(x: f32): f32 {
  var y: f32, z: f32;
  x *= 1 / PI;
  y  = floor(x);
  z  = x - y;
  z *= 1.0 - z;
  z *= 3.6 * z + 3.1;
  return select(-z, z, <i32>y & 1);
}

export function cos(x: f32): f32 {
  return sin(x + PI * .5);
}
```

**Comment by petersalomonsen** [comment]
Thanks @MaxGraey . I've switched to your sin/cos in my synth code and it seems to work great :-)

https://github.com/petersalomonsen/javascriptmusic/commit/b78cb35e8c25bc09ef4a877f6a3c00dd6ab3558b
